# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confernce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('nunm', models.IntegerField(verbose_name='容纳人数')),
            ],
            options={
                'verbose_name_plural': '会议室',
            },
        ),
        migrations.CreateModel(
            name='Confernce_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64, verbose_name='时间段')),
                ('confernce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Confernce', verbose_name='所属会议室')),
            ],
            options={
                'verbose_name_plural': '会议室详细',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='confernce_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Userinfo', verbose_name='预定人'),
        ),
    ]
