# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confernce',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_super',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否是管理员'),
        ),
        migrations.AlterField(
            model_name='confernce',
            name='title',
            field=models.CharField(max_length=32, verbose_name='会议室名称'),
        ),
    ]
